---
functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Сайт должен иметь мобильную версию
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Сайт должен быть доступен на различных устройствах
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
implicit:
  - Должна быть реализована страница "Регистрации пользователя", где вводится информаци, ФИО, Номер телефона, дата рождения, Логин, Пароль, подтвердите пароль, электронная почта
  - После нажатия кнопки зарегистрироваться, должно появиться всплывающее окно, с сообщением, регистрация успешно завершена
  - При регистрации пользователя должны стоять следующие огранечения: ФИО не менее 5 символов, Номер телефона 12 цифр, дата рождения в формате DD.MM.YYYY, логин не менее 2 символов, в логине можно использовать только латиницу и цифры, пароль от 6 до 20 символов, электронная почта должна содержать знак "@"
  - Должна быть реализована страница "Вход", где пользователь вводит свой логин и пароль
  - Если логин и пароль введены вверно, после нажатия по кнопке "Вход", должна открыться главная страница
  - Если логин и пароль введены не вверно, должно появиться надпись, введите правильный логин и пароль, и очиститься формы "логин", "пароль"
  - На сайте должен быть реализован доступ администратору
  - У Администратора должны быть реализованы функции, как "Добавление товара", "Редактирование товара", "Удаление товара", "Просмотр заказов пользователей"
  - Логотип компании должен распологаться слева в шапке сайта
  - При нажатии на логотоп компании должена открываться "Главная страница"
  - В шапке страницы сайта должна быть реализована кнопка "Часто задаваемые вопросы", которая открывает страницу, где описаны часто задаваемые вопросы, и происходит поддержка пользователя в пользовании сайта и консультация по товару и заказам
  - Размер фотографии товара должен быть размером 300 х 250 пикселей
  - Переключение между страницами товара на "Главной странице", должен находиться вверху списка и внизу списка
  - При добавлении товара в корзину должна открываться всплывающее окно, где вводится количество добавляемого товара в корзину
  - Фильтрация товара и поиск товара должны распологаться в меню страницы
  - На странице "Корзина товара", должны быть реализованы функции "Очистить корзину", "Удалить товар", "Оформить заказ"
  - При нажатии на кнопку "Оформить заказ", должно открыться всплывающее окно, где у покупателя отображается добавленный товар в корзине, цена за каждую позицию товара, сумма товара добавленных в корзину и кнопка "Подтвердить заказ"
  - После подтверждения заказа у пользователя должно появиться всплывающее окно, где отображается "Заказ успешно оформлен, в ближайшее время с вами свяжется наш оператор"
  - У пользователя должен быть доступ к странице "Мои заказы", где отображается следующая информация номер заказа, товар в заказе, цена за каждый товар в заказе, сумма стоимости заказа, время заказа
  - Фильтрация товара должна происходить по следующим категориям: поиск по ключевым словам, производитель товара, наличие товара на складе, цена товара, рейтинг товара
  - Внизу главной страницы сайта должна находиться информация о магазине, юридический адрес,  телефон горячих линий компании
