---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность просмотра товара на странице и в каталоге, где выводятся название, рейтинг, цена со скидкой и без
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность добавлять товар в корзину и продолжать выбирать товары в каталоге
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен иметь мобильную версию
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Логотип компании должен распологаться слева в шапке сайта
  - При нажатии на логотоп компании должена открываться "Главная страница"
  - Размер фотографии товара должен быть размером 300 х 250 пикселей
  - Переключение между страницами товара на "Главной странице", должен находиться вверху списка и внизу списка
  - При добавлении товара в корзину должна открываться всплывающее окно, где вводится количество добавляемого товара в корзину
  - Фильтрация товара и поиск товара должны распологаться в меню страницы
  - На странице "Корзина товара", должны быть реализованы функции "Очистить корзину", "Удалить товар", "Оформить заказ"
  - При нажатии на кнопку "Оформить заказ", должно открыться всплывающее окно, где у покупателя отображается добавленный товар в корзине, цена за каждую позицию товара, сумма товара добавленных в корзину и кнопка "Подтвердить заказ"
  - После подтверждения заказа у пользователя должно появиться всплывающее окно, где отображается "Заказ успешно оформлен, в ближайшее время с вами свяжется наш оператор"
  - У пользователя должен быть доступ к странице "Мои заказы", где отображается следующая информация номер заказа, товар в заказе, цена за каждый товар в заказе, сумма стоимости заказа, время заказа
  - Фильтрация товара должна происходить по следующим категориям поиск по ключевым словам, производитель товара, наличие товара на складе, цена товара, рейтинг товара
  - Внизу главной страницы сайта должна находиться информация о магазине, юридический адрес,  телефон горячих линий компании
